name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20, 22, 24 ]
    name: Test - Node v${{ matrix.node-version }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: codecov
        uses: codecov/codecov-action@v5
        with:
          flags: tests-node-v${{ matrix.node-version }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
